# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000  # Choose an available node port number (30000-32767)
  type: NodePort
